# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 4.1.0
_src_path: gh:epics-containers/deployment-template-argocd
argocd_project: bl47p
argocd_server: argocd.diamond.ac.uk
cluster_name_apps: argus
cluster_name_services: pollux
cluster_namespace_apps: p47-beamline
cluster_namespace_services: p47-beamline
deployment_repo: https://github.com/epics-containers/p47-deployment
description: p47 IOC Instances and Services ArgoCD deployments
git_platform: github.com
github_org: epics-containers
ioc_group: p47
logging_url: https://graylog2.diamond.ac.uk/search?rangetype=relative&fields=message%2Csource&width=1489&highlightMessage=&relative=172800&q=pod_name%3A{service_name}*
services_release: main
services_repo: https://github.com/epics-containers/p47-services
