apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: p47
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: bl47p
  destination:
    name: pollux
    namespace: p47-beamline
  source:
    path: apps
    repoURL: https://github.com/epics-containers/p47-deployment
    targetRevision: main
    helm:
      version: v3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true