# yaml-language-server: $schema=https://github.com/epics-containers/ec-helm-charts/releases/download/5.5.0/argocd-apps.schema.json

# This file configures an ArgoCD app of apps that represent a
# group of beamline or accelerator IOCs and services. The configuration of the
# services are in the separate repo indicated by repoURL.

# This repository only controls which services and which versions of those
# services should be running on the cluster. It is recommended that this repo
# be updated by a CI/CD pipeline or configuration tools only.

project: p47-beamline
destination:
  name: pollux
  namespace: p47-beamline
source:
  repoURL: https://github.com/epics-containers/p47-services
  targetRevision: main

services:
  p47-epics-pvcs:
  p47-rabbitmq:
  p47-blueapi:
  p47-nexus:
  p47-proxy:
  p47-epics-gateways:
  bl47p-synoptic:
  p47-epics-opis:
    labels:
      description: its-opis-ok
  bl47p-mo-ioc-01:
  bl47p-ea-simdet:
  bl47p-ea-fastcs-01:
    enabled: true
    targetRevision: podbench-hotfix-claim
    labels:
      description: example-fastcs
